#pragma once

enum GameStateName
{
    MENU,
    LEVEL,
    EXIT,
};

enum TextureName
{
    MENU_TLO,
    PRZYCISK_GRA,
    PRZYCISK_GRA_AKTYWNY,
    PRZYCISK_WYJSCIE,
    PRZYCISK_WYJSCIE_AKTYWNY,
    NULL_TEXTURE,

    LEVEL_FLOOR,
    LEVEL_ROBBO,
    LEVEL_BUSH,
    LEVEL_WALL,
    LEVEL_DOOR,
    LEVEL_MIRROR,
    LEVEL_CHEST,
    LEVEL_PUSH,
    LEVEL_BOMB,
    LEVEL_SURPRISE,
    LEVEL_SCREW,
    LEVEL_KEY,
    LEVEL_AMMO,
    LEVEL_BULLET,
    LEVEL_BLASTER,
    LEVEL_LIFE,

    LEVEL_SMOKE01,
    LEVEL_SMOKE02,
    LEVEL_SMOKE03,
    LEVEL_SMOKE04,
    LEVEL_SMOKE05,
    LEVEL_SMOKE06,
    LEVEL_SMOKE07,

    LEVEL_MAGNET_UP,
    LEVEL_MAGNET_DOWN,
    LEVEL_MAGNET_LEFT,
    LEVEL_MAGNET_RIGHT,

    LEVEL_LASER_SHOOTER_UP,
    LEVEL_LASER_SHOOTER_DOWN,
    LEVEL_LASER_SHOOTER_LEFT,
    LEVEL_LASER_SHOOTER_RIGHT,

    LEVEL_LASER_HEAD_UP,
    LEVEL_LASER_HEAD_DOWN,
    LEVEL_LASER_HEAD_LEFT,
    LEVEL_LASER_HEAD_RIGHT,

    LEVEL_LASER_BODY_VERTICAL,
    LEVEL_LASER_BODY_HORIZONTAL,

    LEVEL_CANNON_UP,
    LEVEL_CANNON_DOWN,
    LEVEL_CANNON_LEFT,
    LEVEL_CANNON_RIGHT,

    LEVEL_MOVING_CANNON,

    LEVEL_BLASTER_CANNON_UP,
    LEVEL_BLASTER_CANNON_DOWN,
    LEVEL_BLASTER_CANNON_LEFT,
    LEVEL_BLASTER_CANNON_RIGHT,

    LEVEL_SHIP_CLOSED,
    LEVEL_SHIP_OPEN,

    LEVEL_GOLDEN_SEAHORSE_UP,
    LEVEL_GOLDEN_SEAHORSE_DOWN,
    LEVEL_GOLDEN_SEAHORSE_LEFT,
    LEVEL_GOLDEN_SEAHORSE_RIGHT,

    LEVEL_PURPLE_SEAHORSE_UP,
    LEVEL_PURPLE_SEAHORSE_DOWN,
    LEVEL_PURPLE_SEAHORSE_LEFT,
    LEVEL_PURPLE_SEAHORSE_RIGHT,

    LEVEL_COOKIE_MONSTER_LEFT,
    LEVEL_COOKIE_MONSTER_RIGHT,

    LEVEL_EYE,

    LEVEL_PANEL,
};

enum GameObjectName
{
    WALL,
    BUSH_WALL,
    DOOR,
    MIRROR,
    BUSH,
    SHIP,
    MAGNET,

    CHEST,
    PUSH,
    BOMB,
    SURPRISE,

    SCREW,
    KEY,
    AMMO,
    LIFE,
    BULLET,
    BLASTER,
    SMOKE,

    LASER_SHOOTER,
    LASER_HEAD,
    LASER_BODY,

    CANNON,
    MOVING_CANNON,
    BLASTER_CANNON,
    ROTATING_CANNON,

    GOLDEN_SEAHORSE,
    PURPLE_SEAHORSE,
    COOKIE_MONSTER,
    EYE,

    ROBBO,

    NULL_OBJECT,
};

enum RobboAction
{
    GO_LEFT,
    GO_RIGHT,
    GO_UP,
    GO_DOWN,

    SHOT_LEFT,
    SHOT_RIGHT,
    SHOT_UP,
    SHOT_DOWN,

    SELF_DESTRUCT,

    NOTHING,
};

enum Direction
{
    LEFT,
    RIGHT,
    UP,
    DOWN,
    NULL_DIR,
};

enum Axis
{
    VERTICAL,
    HORIZONTAL,
};